pipeline {
  agent any

  environment {
    DEV_METADATA = '/var/lib/jenkins/workspace/inbuddy/dev'
  }

  stages {
    stage('.env, start.sh 복사') {
      steps {
        sh "rm -f ./.env && cp ${env.DEV_METADATA}/scheduler/.env ./.env"
        sh "rm -f ./start.sh && cp ${env.DEV_METADATA}/scheduler/start.sh ./start.sh"
      }
    }

    stage('Container 재시작') {
      steps {
        sh "docker compose -f ${env.DEV_METADATA}/docker-compose-dev.yml restart dev-scheduler"
      }
    }
  }
}
