def build() {
    // 환경 변수 설정
    DEV_METADATA = '/var/lib/jenkins/workspace/inbuddy/dev'

    // .env, start.sh 복사
    sh "rm -f ./.env && cp ${DEV_METADATA}/scheduler/.env ./.env"
    sh "rm -f ./start.sh && cp ${DEV_METADATA}/scheduler/start.sh ./start.sh"

    // Container 재시작
    sh "docker compose -f ${DEV_METADATA}/docker-compose-dev.yml restart dev-scheduler"
}

return this