pipeline {
  agent any

  environment {
    DEV_METADATA = '/var/lib/jenkins/workspace/inbuddy/dev'

    SRC_RESOURCES = './src/main/resources/'
  }

  tools {
      gradle 'default'
  }

  stages {
    stage('properties 복사') {
      steps {
        sh "rm -f ${env.SRC_RESOURCES}/application.properties && mkdir ${env.SRC_RESOURCES} || true"
        sh "cp ${env.DEV_METADATA}/be/application.properties ${env.SRC_RESOURCES}/application.properties"
      }
    }

    stage('SpringBoot 빌드') {
      steps {
        /** clean and slow build with info **/
        // sh 'chmod +x gradlew && ./gradlew clean --info build'

        /** normal build **/
        // sh 'chmod +x gradlew && ./gradlew build'

        /** fast build **/
        sh 'chmod +x gradlew && ./gradlew bootJar'
      }
    }

    stage('Container 재시작') {
      steps {
        sh "docker compose -f ${env.DEV_METADATA}/docker-compose-dev.yml restart dev-be"
      }
    }
  }
}
